### PR TITLE
updates

### PR DESCRIPTION
**Pull request by n4t3m**
judge pic updates

fixed old reference to citrushack

### CODE REVIEW

**Comment by minsooerickim** [comment]
headshots need to be like exactly a square. ex 100 x 100. if u look closely on judges, it ain't a complete circle, the sides r cut off. L script

**Comment by n4t3m** [comment]
the world isnt ready for my script

**Comment by minsooerickim** [comment]
@NateM135 ill just merge dis in for now, but u shud def update the script to crop the photos with same width & height 👍

**Comment by minsooerickim** [comment]
o also workflow is feature branch -> dev -> prod (prod is auto deployed by vercel)

**Comment by n4t3m** [comment]
bro how would I script finding the face, the pictures aren't all centered around someones face 

i love doing manual work wooooo

**Comment by minsooerickim** [comment]
> g manual work wooooo

machine learning!

**Comment by n4t3m** [comment]
gcp does indeed have a service for this

**Pull request merged**
