### PR TITLE
Rfairooz/sponsors

### LINKED ISSUE #11: make sponsors section
make a separate "sponsors" component

- put placeholder text/logos
- you can reference the sponsors page on here https://www.citrushack.com/

### PR DESCRIPTION
**Pull request by rfairooz**
I changed the map for the logos and now it renders each tier name separately. There is still styling and stuff left to do. Let me know if this is expected structure for the section. 

Site pics:
Screen Shot 2022-09-12 at 4 39 56 PM
Screen Shot 2022-09-12 at 4 40 10 PM

### CODE REVIEW

**Comment by minsooerickim** [comment]
idk what all the cache stuff is but you should probs just delete all those

**Comment by minsooerickim** [comment]
also run `yarn format` to format you code with prettier. looks like its not passing the check

**Comment by minsooerickim** [comment]
@rfairooz check the deployment messages as well. its not passing rn; also reply to my comment once ur done addressing my comments so I can check

image

you can run `yarn run build` to see if everything passes correctly

**Comment by rfairooz** [comment]
> @rfairooz check the deployment messages as well. its not passing rn; also reply to my comment once ur done addressing my comments so I can check
> 
> image
> 
> you can run `yarn run build` to see if everything passes correctly

I keep on getting a "worker error", im trying to look into it. Can you check? 
Screen Shot 2022-09-12 at 4 43 38 PM
Screen Shot 2022-09-12 at 4 43 46 PM

**Comment by rfairooz** [comment]
> idk what all the cache stuff is but you should probs just delete all those

yea I don't know where all that came from. I'll delete and push again.

**Comment by minsooerickim** [comment]
> > @rfairooz check the deployment messages as well. its not passing rn; also reply to my comment once ur done addressing my comments so I can check
> > image
> > you can run `yarn run build` to see if everything passes correctly
> 
> I keep on getting a "worker error", im trying to look into it. Can you check? Screen Shot 2022-09-12 at 4 43 38 PM Screen Shot 2022-09-12 at 4 43 46 PM

well, it says it cant find the module, so first check if that module is defined in ur package.json and if it is, run yarn install to install it. then try running build again?

**Pull request closed without merging**
