### PR TITLE
make support section

### PR DESCRIPTION
**Pull request by nibchao**
i closed my previous pull request to correct my mistake of making a branch from my existing branch instead of dev branch. i hope to have interpreted minsoo's code suggestions correctly and done the requested changes.

unknown

### CODE REVIEW

**Comment by minsooerickim** [comment]
@nibchao when i said make a component i meant use mapping to pass in info to a single component

so you would do something like

```
const info = [
{
title:'mentors'
},
{
title:'volunteers'
},
}

export function {
info.map({title, ...}) {
    <CREATE COMPONENT title=title, ...>
}
}
```

and obviously, put more stuff along with title like descriptions and what not. this way, we are creating one component that we use as a template and we can feed in different information but they would all load in the same fashion/style.

**Comment by minsooerickim** [comment]
> 

also, this works for now. but in the future, you should look into `git rebase`

**Comment by nibchao** [comment]
@minsooerickim i adjusted my code to follow what you were expecting with making the information into components. i know you said on my previous support-section pull request to delete yarn.lock to make github not have it under files changed, but i still see it as deleting a lot of lines of code on the pull request. 
image 
image

**Comment by minsooerickim** [comment]
> now you said on my previous support-section pull request to d

yea so what you need to do is delete them but DON'T commit the deleted changes. Only commute the support section related changes. Lmk if u have further questions,i can help if u need more help

**Comment by nibchao** [comment]
@minsooerickim did i do what you said correctly? i readded the yarn.lock file from the dev branch and committed + pushed it so that there are only this many LOC removed instead of the -3250 before. i then deleted the yarn.lock from my local branch and did not push the deletion.
image

**Pull request closed without merging**
